# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IdentificacaodePlacas(object):
    def setupUi(self, IdentificacaodePlacas):
        IdentificacaodePlacas.setObjectName("IdentificacaodePlacas")
        IdentificacaodePlacas.resize(347, 148)
        self.centralwidget = QtWidgets.QWidget(IdentificacaodePlacas)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_iniciar.setGeometry(QtCore.QRect(10, 10, 91, 26))
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.btn_parar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_parar.setGeometry(QtCore.QRect(10, 40, 91, 26))
        self.btn_parar.setObjectName("btn_parar")
        self.btn_limpar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpar.setGeometry(QtCore.QRect(10, 70, 91, 26))
        self.btn_limpar.setObjectName("btn_limpar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 191, 61))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 201, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 84, 26))
        self.pushButton.setObjectName("pushButton")
        IdentificacaodePlacas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IdentificacaodePlacas)
        self.statusbar.setObjectName("statusbar")
        IdentificacaodePlacas.setStatusBar(self.statusbar)

        self.retranslateUi(IdentificacaodePlacas)
        QtCore.QMetaObject.connectSlotsByName(IdentificacaodePlacas)

    def retranslateUi(self, IdentificacaodePlacas):
        _translate = QtCore.QCoreApplication.translate
        IdentificacaodePlacas.setWindowTitle(_translate("IdentificacaodePlacas", "Identificacao Placas"))
        self.btn_iniciar.setText(_translate("IdentificacaodePlacas", "Iniciar"))
        self.btn_parar.setText(_translate("IdentificacaodePlacas", "Parar"))
        self.btn_limpar.setText(_translate("IdentificacaodePlacas", "Limpar Pasta"))
        self.label.setText(_translate("IdentificacaodePlacas", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("IdentificacaodePlacas", "Pressione \'ESC\'  para  parar"))
        self.pushButton.setText(_translate("IdentificacaodePlacas", "Abrir Pasta"))
